#!/bin/bash -x
   
#Install Docker

sudo apt update -y
sudo apt-get remove docker docker-engine docker.io -y
sudo apt install -y docker.io

### Install Kubectl ###


curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl

sudo chmod +x ./kubectl 
sudo mv ./kubectl /usr/local/bin/kubectl


### Install Minikube ###

curl -LO https://github.com/kubernetes/minikube/releases/download/v1.12.0/minikube_1.12.0-0_amd64.deb
sudo dpkg -i minikube_1.12.0-0_amd64.deb
sudo apt-get install -y conntrack
sudo minikube config set vm-driver none
sudo minikube start --vm=true 
sudo chown -R $USER $HOME/.minikube; chmod -R u+wrx $HOME/.minikube
sudo minikube addons enable ingress

### Install nodejs ###

curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
sudo apt install nodejs -y

### Install Helm ###

sudo snap install helm --classic

rm -f minikube_1.12.0-0_amd64.deb
